FROM resin/%%RESIN_MACHINE_NAME%%-python:3

WORKDIR /usr/src/app

COPY buildstatus ./buildstatus

RUN pip3 install --no-cache-dir -r buildstatus/requirements.txt

RUN pip3 install --no-cache-dir ./buildstatus

ENV INITSYSTEM on

CMD ["buildstatus.py"]
