FROM resin/%%RESIN_MACHINE_NAME%%-python:3

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

COPY buildstatus.py ./

ENV INITSYSTEM on

CMD ["python3", "buildstatus.py"]
